### ISSUE TITLE
Compilation fails when using camlp4 package with opam 2.0.2 (sandboxing issue ?)

### ISSUE THREAD

**Issue by jserot** [camlp4/camlp4#147] opened 2019-01-30 15:16 UTC
When rebuilding for Opam 2.0.2 a package making use of camlp4 i got the following error:

```
#=== ERROR while compiling lascar.0.5 =========================================#
# context     2.0.2 | macos/x86_64 | base-bigarray.base base-threads.base base-unix.base ocaml-base-compiler.4.06.0 | pinned(git+file:///Users/jserot/Dev/ml/lascar#master#a0c45fe3)
# path        ~/.opam/4.06.0/.opam-switch/build/lascar.0.5
# command     ~/.opam/opam-init/hooks/sandbox.sh build make
# exit-code   2
# env-file    ~/.opam/log/lascar-56230-b0c309.env
# output-file ~/.opam/log/lascar-56230-b0c309.out
### output ###
# [...]
# ocamlfind ocamlc  -for-pack Utils -c option.ml
...
# ocamlfind ocamlc  -for-pack Utils -package camlp4 -syntax camlp4o -c listExt.ml 
# File "listExt.ml", line 1:
# Error: I/O error: /tmp/ocamlpp027236: Operation not permitted
# make[1]: *** [listExt.cmo] Error 2
```
The package was compiling perfectly well under opam 1.2.
My guess is that the problem is related to the sandboxing technique now used by opam 2.0.2.
More precisely, it seems that some functions in `camlp4` are trying to write in `/tmp`, which is now forbidden ?

Am i right ?
If yes, what's the correct way to fix this.

```
$ opam show camlp4

<><> camlp4: information on all versions ><><><><><><><><><><><><><><><><><>  🐫 
name                   camlp4
all-installed-versions 4.03+1 [4.03.0]  4.06+1 [4.06.0]
all-versions           4.01  4.01+system  4.02+1  4.02+2  4.02+3  4.02+4  4.02+6  4.02+7  4.02+system  4.02.0-1modular-implicits  4.03+1
                       4.03+system  4.04+1  4.04+system  4.05+1  4.05+system  4.06+1  4.06+system  4.07+1  4.07+system

<><> Version-specific details <><><><><><><><><><><><><><><><><><><><><><><>  🐫 
version       4.06+1
...
```

**Comment by ghost** [comment] 2019-01-30 16:17
Writing in the temporary directory should definitely work. The compiler creates many temporary files for instance.

I would try to strace the failing command to see what system call is failing exactly.

**Comment by gasche** [comment] 2019-01-30 17:17
You can disable sandboxing at the opam level by using `opam init --disable-sandboxing`. However, this is not a bugfix, as it risks introducing back the problems that sandboxing was introduced to solve (namely: faulty installation scripts that would remove things belonging to other packages, or even files of the user; and I seem to remember that camlp4, or another core package, was affected by such a bug in the past).

It's not clear from the report what exactly was forbidden, but it looks like it might be the creation of a file in `/tmp`. This is a bit surprising, as surely other packages use it and the sandbox must allow it. I feel that this is an opam issue, rather than a camlp4 issue; @AltGr, would you by chance know where/who to ask?

**Comment by jserot** [comment] 2019-01-31 09:22
Seems the problem is my local `sandbox`script : 

[https://github.com/ocaml/opam-repository/issues/13339](url)

**Comment by gasche** [comment] 2019-01-31 10:28
Thanks! I'm closing the issue as it turns out not to be camlp4-specific.

**Closed as completed** 2019-01-31 10:28 UTC
